require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Sub::ShoutBoxesController do

  # This should return the minimal set of attributes required to create a valid
  # Sub::ShoutBox. As you add validations to Sub::ShoutBox, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Sub::ShoutBoxesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sub_shout_boxes as @sub_shout_boxes" do
      shout_box = Sub::ShoutBox.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sub_shout_boxes).should eq([shout_box])
    end
  end

  describe "GET show" do
    it "assigns the requested sub_shout_box as @sub_shout_box" do
      shout_box = Sub::ShoutBox.create! valid_attributes
      get :show, {:id => shout_box.to_param}, valid_session
      assigns(:sub_shout_box).should eq(shout_box)
    end
  end

  describe "GET new" do
    it "assigns a new sub_shout_box as @sub_shout_box" do
      get :new, {}, valid_session
      assigns(:sub_shout_box).should be_a_new(Sub::ShoutBox)
    end
  end

  describe "GET edit" do
    it "assigns the requested sub_shout_box as @sub_shout_box" do
      shout_box = Sub::ShoutBox.create! valid_attributes
      get :edit, {:id => shout_box.to_param}, valid_session
      assigns(:sub_shout_box).should eq(shout_box)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sub::ShoutBox" do
        expect {
          post :create, {:sub_shout_box => valid_attributes}, valid_session
        }.to change(Sub::ShoutBox, :count).by(1)
      end

      it "assigns a newly created sub_shout_box as @sub_shout_box" do
        post :create, {:sub_shout_box => valid_attributes}, valid_session
        assigns(:sub_shout_box).should be_a(Sub::ShoutBox)
        assigns(:sub_shout_box).should be_persisted
      end

      it "redirects to the created sub_shout_box" do
        post :create, {:sub_shout_box => valid_attributes}, valid_session
        response.should redirect_to(Sub::ShoutBox.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sub_shout_box as @sub_shout_box" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sub::ShoutBox.any_instance.stub(:save).and_return(false)
        post :create, {:sub_shout_box => { "id" => "invalid value" }}, valid_session
        assigns(:sub_shout_box).should be_a_new(Sub::ShoutBox)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sub::ShoutBox.any_instance.stub(:save).and_return(false)
        post :create, {:sub_shout_box => { "id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sub_shout_box" do
        shout_box = Sub::ShoutBox.create! valid_attributes
        # Assuming there are no other sub_shout_boxes in the database, this
        # specifies that the Sub::ShoutBox created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sub::ShoutBox.any_instance.should_receive(:update_attributes).with({ "id" => "1" })
        put :update, {:id => shout_box.to_param, :sub_shout_box => { "id" => "1" }}, valid_session
      end

      it "assigns the requested sub_shout_box as @sub_shout_box" do
        shout_box = Sub::ShoutBox.create! valid_attributes
        put :update, {:id => shout_box.to_param, :sub_shout_box => valid_attributes}, valid_session
        assigns(:sub_shout_box).should eq(shout_box)
      end

      it "redirects to the sub_shout_box" do
        shout_box = Sub::ShoutBox.create! valid_attributes
        put :update, {:id => shout_box.to_param, :sub_shout_box => valid_attributes}, valid_session
        response.should redirect_to(shout_box)
      end
    end

    describe "with invalid params" do
      it "assigns the sub_shout_box as @sub_shout_box" do
        shout_box = Sub::ShoutBox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sub::ShoutBox.any_instance.stub(:save).and_return(false)
        put :update, {:id => shout_box.to_param, :sub_shout_box => { "id" => "invalid value" }}, valid_session
        assigns(:sub_shout_box).should eq(shout_box)
      end

      it "re-renders the 'edit' template" do
        shout_box = Sub::ShoutBox.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sub::ShoutBox.any_instance.stub(:save).and_return(false)
        put :update, {:id => shout_box.to_param, :sub_shout_box => { "id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sub_shout_box" do
      shout_box = Sub::ShoutBox.create! valid_attributes
      expect {
        delete :destroy, {:id => shout_box.to_param}, valid_session
      }.to change(Sub::ShoutBox, :count).by(-1)
    end

    it "redirects to the sub_shout_boxes list" do
      shout_box = Sub::ShoutBox.create! valid_attributes
      delete :destroy, {:id => shout_box.to_param}, valid_session
      response.should redirect_to(sub_shout_boxes_url)
    end
  end

end
