dictionary:
  alliance: crew
  alliances: crews
  individual: pirate
  stats: information stuff
  english: non pirate
  operations: things
  science: magic
  home: port
  contact: message
  language: scrawl
  sitemap: chart
  credit: doubloon
  credits: doubloons
  register: board
  leaderboard: rankings
