TheSkyMap.CurrentPlayer = DS.Model.extend(
  name: DS.attr("string")
  email: DS.attr("string")
  profile_id: DS.attr("number")
  user_signed_in: DS.attr("boolean")
  unread_msg_count: DS.attr("number")
  home_x: DS.attr("number")
  home_y: DS.attr("number")
  game_map_id: DS.attr("number")
  total_score: DS.attr("number")
  total_income: DS.attr("number")
  total_income_special: DS.attr("number")
  currency_available: DS.attr("number")
  currency_available_special: DS.attr("number")
  player_options: DS.attr('raw')
)

